#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Beganovich\Snappdf\Command\DownloadChromiumCommand;
use Beganovich\Snappdf\Command\UpdateActiveBinary;
use Symfony\Component\Console\Application;

$application = new Application('Snappdf');

$application->add(new DownloadChromiumCommand());
$application->add(new UpdateActiveBinary());

$application->run();
